---
#
# User configuration
#
user:
  name: vitezfh
  full_name: vitezfh
  primary_group: vitezfh
  additional_groups: docker,wheel,audio,docker
  # /bin/bash or /bin/zsh
  shell: /bin/zsh
  # See country list by running `reflector --list-countries`
  country: "Germany"

git:
  name: "{{ user['full_name'] }}"
  # obfuscated a little so bots won't find it
  email_b64: "dml0ZXpmaEBnbWFpbC5jb20K"
  # can be "cache", "store", "osxkeychain", or "manager"
  helper: "cache"
  # can be "true" or "false"
  rebase: "true"
  # see this https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---color-movedltmodegt
  colorMoved: "zebra"

#
# Miscellaneous
#

# desktop environment to install
# "kde" or "gnome"
# true to only install gpu drivers and fonts, etc.
desktop: true

# To install multimedia packages
media: true

# To install gaming packages
gaming: true

# only AMD or Intel CPUs are currently supported
# true or false
microcode: true

# whether to enable printing/scanning or not
# true or false
printing_scanning: true

# whether to detect the scanner or not
# true or false
detect_scanner: true

# whether to enable bluetooth or not
# true or false
bluetooth: true

# whether to install sunshine (game streaming)
# true or false
sunshine: true

# how many parallel downloads to run at once
pacman:
  parallel_downloads: 10

# set aur helper
# supported helpers are here https://github.com/kewlfft/ansible-aur#kewlfftauraur-module
aur_helper: yay

#
# Services
#

# if not using LVM, disable it
# true or false
disable_lvm: true

# if not using systemd homed, disable it
# true or false
disable_systemd_homed: true

#
# Packages
#
packages:
  general:
    - cadaver #cli webdav client
    ### GUI
    - firefox
    - chromium
    ###
    - dosfstools
    - e2fsprogs
    - exfatprogs
    - ffmpeg
    - fwupd
    - gnupg
    - gparted
    - gst-libav
    - gst-plugins-bad
    - gst-plugins-base
    - gst-plugins-good
    - gvfs
    - gvfs-afc
    - gvfs-gphoto2
    - gvfs-smb
    - htop
    - ifuse
    - inetutils
    - iotop
    - iperf3
    - iputils
    - kubectl
    - libimobiledevice
    - linux-firmware
    - man
    - man-db
    - man-pages
    - minicom
    - mkvtoolnix-cli
    - networkmanager
    - ntfs-3g
    - nvme-cli
    - openssh
    - openvpn
    ### Audio
    - pipewire
    - pipewire-alsa
    - alsa-firmware
    - alsa-plugins
    - alsa-utils
    ###
    - pkgstats
    - usbutils
    - vi
    - wireguard-tools
    - wireplumber
    - wpa_supplicant
    - avahi
    # Needed for GTK apps that run as Flatpaks
    - xdg-desktop-portal-gtk
    - xfsprogs
    - git
  shell:
    - sudo
    - bash
    - bash-completion
    - stow
    - jq
    - screen
    - wget
    - curl
    - rsync
    - ncdu
    - tree
    - fzf
  archiving:
    - 7zip
    - unrar-free
    - unzip
    - zstd
    - zip
  development:
    - code
    - neovim
    - docker
    - docker-compose
    - picocom # serial console, UART
    - esphome
  media:
    - yt-dlp
    - vlc
    - vlc-plugins-all
    - mpv
    - lame
  gaming:
    - steam
    - lutris
    - wine
    - wine-mono
    - wine-gecko
  printing_scanning:
    - cups
    - cups-pdf
    - cups-filters
    - nss-mdns
    - sane
    - sane-airscan
    - simple-scan
    - avahi
  fonts:
  - adobe-source-code-pro-fonts
  - adobe-source-han-sans-jp-fonts
  - adobe-source-sans-pro-fonts
  - adobe-source-serif-pro-fonts
  - gnu-free-fonts
  - noto-fonts
  - noto-fonts-cjk
  - noto-fonts-emoji
  - powerline-fonts
  - ttf-anonymous-pro
  - ttf-dejavu
  - otf-cascadia-code
  - ttf-cascadia-code
  - ttf-hack
  - ttf-liberation

aur_packages:
  general:
  printing_scanning:

flatpaks:
  - com.github.tchx84.Flatseal
  - io.github.flattool.Warehouse
  - us.zoom.Zoom
  # See other themes here
  # flatpak remote-ls flathub | grep org.gtk.Gtk3theme

vscode_extension_list:
  - eamodio.gitlens
  - golang.go
  - ms-python.python
  - redhat.ansible
  - redhat.vscode-xml
  - redhat.vscode-yaml
