---
#
# Mars specific configuration
#

user:
  name: vitezfh
  full_name: vitezfh
  primary_group: vitezfh
  additional_groups: docker,wheel,audio,docker
  shell: /bin/zsh
  country: "Germany"

git:
  name: "{{ user['full_name'] }}"
  email_b64: "dml0ZXpmaEBnbWFpbC5jb20K"
  helper: "cache"
  rebase: "true"
  colorMoved: "zebra"

# Mars specific flags
sunshine: true
