---
- name: Install bluetooth packages
  community.general.pacman:
    name:
      - bluez
      - bluez-utils
      - bluez-tools
    state: present
  become: true

- name: Start systemd service - bluetooth.service
  ansible.builtin.systemd:
    name: bluetooth.service
    state: started
    enabled: yes
  become: true
