---
- name: Create user
  ansible.builtin.user:
    name: "{{ user.name }}"
    comment: "{{ user.full_name }}"
    groups: "{{ user.additional_groups }}"
    append: yes
    shell: "{{ user.shell }}"
    state: present
  become: true
  register: user_created

- name: Git config user.name
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ git.name }}"

- name: Git config user.email
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ git.email_b64 | b64decode }}"

- name: Git config credential.helper
  community.general.git_config:
    name: credential.helper
    scope: global
    value: "{{ git.helper }}"

- name: Git config pull.rebase
  community.general.git_config:
    name: pull.rebase
    scope: global
    value: "{{ git.rebase }}"

- name: Git config diff.colorMoved
  community.general.git_config:
    name: diff.colorMoved
    scope: global
    value: "{{ git.colorMoved }}"

- name: Install VS Code extensions
  ansible.builtin.shell: code --install-extension {{ item }}  # noqa command-instead-of-shell
  with_items: "{{ (default_vscode_extension_list | default([])) + (vscode_extension_list | default([])) + (host_vscode_extension_list | default([])) }}"
  changed_when: no

- name: Clone dotfiles
  ansible.builtin.git:
    repo: https://github.com/staernid/dotfiles.git
    dest: "/home/{{ user.name }}/dotfiles"
    version: master
  become: true
  become_user: "{{ user.name }}"

- name: Copy dotfile config
  ansible.builtin.copy:
    src: "/home/{{ user.name }}/dotfiles/dotfile.conf.dist"
    dest: "/home/{{ user.name }}/dotfiles/dotfile.conf"
    remote_src: yes
    force: false
    mode: '0644'
  become: true
  become_user: "{{ user.name }}"

- name: Deploy dotfiles
  ansible.builtin.command:
    cmd: ./deploy.sh
    chdir: "/home/{{ user.name }}/dotfiles"
  become: true
  become_user: "{{ user.name }}"
  loop: [1, 2]
  changed_when: true

- name: Update makepkg configuration file
  ansible.builtin.template:
    src: makepkg.conf
    dest: "/home/{{ user.name }}/.makepkg.conf"
    backup: no
    owner: "{{ user.name }}"
    group: "{{ user.primary_group }}"
    mode: '0644'

- name: Enable lingering for user
  ansible.builtin.command:
    cmd: "loginctl enable-linger {{ user.name }}"
    creates: "/var/lib/systemd/linger/{{ user.name }}"
  become: true

- name: Start systemd service - xdg-user-dirs.service
  ansible.builtin.systemd:
    name: xdg-user-dirs.service
    state: started
    enabled: yes
    scope: user
  become: true
  become_user: "{{ user.name }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ user_created.uid }}"
